/*
 * Muse API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Unity.Muse.Chat.Client.OpenAPIDateConverter;

namespace Unity.Muse.Chat.Model
{
    /// <summary>
    /// AssistantModelsMuseRequestsModelParameters
    /// </summary>
    [DataContract(Name = "assistant__models__muse__requests__ModelParameters")]
    internal partial class AssistantModelsMuseRequestsModelParameters
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssistantModelsMuseRequestsModelParameters" /> class.
        /// </summary>
        /// <param name="temperature">Controls randomness, higher temperature means more diversity.</param>
        /// <param name="seed">Response generation seed.</param>
        public AssistantModelsMuseRequestsModelParameters(decimal temperature = default(decimal), int seed = default(int))
        {
            this.Temperature = temperature;
            this.Seed = seed;
        }

        /// <summary>
        /// Controls randomness, higher temperature means more diversity.
        /// </summary>
        /// <value>Controls randomness, higher temperature means more diversity.</value>
        [DataMember(Name = "temperature", EmitDefaultValue = false)]
        public decimal Temperature { get; set; }

        /// <summary>
        /// Response generation seed.
        /// </summary>
        /// <value>Response generation seed.</value>
        [DataMember(Name = "seed", EmitDefaultValue = false)]
        public int Seed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AssistantModelsMuseRequestsModelParameters {\n");
            sb.Append("  Temperature: ").Append(Temperature).Append("\n");
            sb.Append("  Seed: ").Append(Seed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
