/*
 * Muse API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Unity.Muse.Chat.Client.OpenAPIDateConverter;

namespace Unity.Muse.Chat.Model
{
    /// <summary>
    /// An enumeration.
    /// </summary>
    /// <value>An enumeration.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    internal enum AssistantModelsMuseRequestsSentiment
    {
        /// <summary>
        /// Enum Positive for value: positive
        /// </summary>
        [EnumMember(Value = "positive")]
        Positive = 1,

        /// <summary>
        /// Enum Negative for value: negative
        /// </summary>
        [EnumMember(Value = "negative")]
        Negative = 2
    }

}
