/*
 * Muse API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Unity.Muse.Chat.Client.OpenAPIDateConverter;

namespace Unity.Muse.Chat.Model
{
    /// <summary>
    /// Chat request, to chat with Muse Chat.
    /// </summary>
    [DataContract(Name = "ChatRequest")]
    internal partial class ChatRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChatRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ChatRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ChatRequest" /> class.
        /// </summary>
        /// <param name="prompt">User message to Muse Chat. (required)</param>
        /// <param name="conversationId">conversationId</param>
        /// <param name="streamResponse">Whether to stream Muse Chat response. (required)</param>
        /// <param name="organizationId">The ID of the Unity organization. (required)</param>
        /// <param name="unityVersions">unityVersions</param>
        /// <param name="dependencyInformation">dependencyInformation</param>
        /// <param name="projectSummary">projectSummary</param>
        /// <param name="mediationSystemPrompt">mediationSystemPrompt</param>
        /// <param name="skipPlanning">Whether to skip planning system or not.</param>
        /// <param name="tags">List of tags associated with chat request</param>
        /// <param name="planningParams">planningParams</param>
        /// <param name="mediationParams">mediationParams</param>
        /// <param name="seed">seed</param>
        /// <param name="context">context</param>
        /// <param name="hideReferences">hideReferences</param>
        /// <param name="museGuard">Whether to use Muse Guard for chat request. Default to False.</param>
        /// <param name="evaluation">Whether the chat request is for evaluation. Default is false.</param>
        /// <param name="structuredPlanning">Whether to use structured generation for planning. Default is false.</param>
        /// <param name="maxStructuredPlanningSteps">Maximum number of structured planning steps. Default to 5.</param>
        /// <param name="structuredMediationRegex">structuredMediationRegex</param>
        /// <param name="planningEndpoint">planningEndpoint</param>
        /// <param name="frontDeskEndpoint">frontDeskEndpoint</param>
        /// <param name="mediationEndpoint">mediationEndpoint</param>
        /// <param name="embeddingEndpoint">embeddingEndpoint</param>
        public ChatRequest(string prompt = default(string), string conversationId = default(string), bool streamResponse = default(bool), string organizationId = default(string), List<string> unityVersions = default(List<string>), Dictionary<string, string> dependencyInformation = default(Dictionary<string, string>), Dictionary<string, string> projectSummary = default(Dictionary<string, string>), string mediationSystemPrompt = default(string), bool skipPlanning = false, List<string> tags = default(List<string>), ModelParameters planningParams = default(ModelParameters), ModelParameters mediationParams = default(ModelParameters), int? seed = default(int?), string context = default(string), bool? hideReferences = default(bool?), bool museGuard = false, bool evaluation = false, bool structuredPlanning = false, int maxStructuredPlanningSteps = 5, string structuredMediationRegex = default(string), PlanningEndpoint planningEndpoint = default(PlanningEndpoint), FrontDeskEndpoint frontDeskEndpoint = default(FrontDeskEndpoint), MediationEndpoint mediationEndpoint = default(MediationEndpoint), EmbeddingEndpoint embeddingEndpoint = default(EmbeddingEndpoint))
        {
            // to ensure "prompt" is required (not null)
            if (prompt == null)
            {
                throw new ArgumentNullException("prompt is a required property for ChatRequest and cannot be null");
            }
            this.Prompt = prompt;
            this.StreamResponse = streamResponse;
            // to ensure "organizationId" is required (not null)
            if (organizationId == null)
            {
                throw new ArgumentNullException("organizationId is a required property for ChatRequest and cannot be null");
            }
            this.OrganizationId = organizationId;
            this.ConversationId = conversationId;
            this.UnityVersions = unityVersions;
            this.DependencyInformation = dependencyInformation;
            this.ProjectSummary = projectSummary;
            this.MediationSystemPrompt = mediationSystemPrompt;
            this.SkipPlanning = skipPlanning;
            this.Tags = tags;
            this.PlanningParams = planningParams;
            this.MediationParams = mediationParams;
            this.Seed = seed;
            this.Context = context;
            this.HideReferences = hideReferences;
            this.MuseGuard = museGuard;
            this.Evaluation = evaluation;
            this.StructuredPlanning = structuredPlanning;
            this.MaxStructuredPlanningSteps = maxStructuredPlanningSteps;
            this.StructuredMediationRegex = structuredMediationRegex;
            this.PlanningEndpoint = planningEndpoint;
            this.FrontDeskEndpoint = frontDeskEndpoint;
            this.MediationEndpoint = mediationEndpoint;
            this.EmbeddingEndpoint = embeddingEndpoint;
        }

        /// <summary>
        /// User message to Muse Chat.
        /// </summary>
        /// <value>User message to Muse Chat.</value>
        [DataMember(Name = "prompt", IsRequired = true, EmitDefaultValue = true)]
        public string Prompt { get; set; }

        /// <summary>
        /// Gets or Sets ConversationId
        /// </summary>
        [DataMember(Name = "conversation_id", EmitDefaultValue = true)]
        public string ConversationId { get; set; }

        /// <summary>
        /// Whether to stream Muse Chat response.
        /// </summary>
        /// <value>Whether to stream Muse Chat response.</value>
        [DataMember(Name = "stream_response", IsRequired = true, EmitDefaultValue = true)]
        public bool StreamResponse { get; set; }

        /// <summary>
        /// The ID of the Unity organization.
        /// </summary>
        /// <value>The ID of the Unity organization.</value>
        [DataMember(Name = "organization_id", IsRequired = true, EmitDefaultValue = true)]
        public string OrganizationId { get; set; }

        /// <summary>
        /// Gets or Sets UnityVersions
        /// </summary>
        [DataMember(Name = "unity_versions", EmitDefaultValue = true)]
        public List<string> UnityVersions { get; set; }

        /// <summary>
        /// Gets or Sets DependencyInformation
        /// </summary>
        [DataMember(Name = "dependency_information", EmitDefaultValue = true)]
        public Dictionary<string, string> DependencyInformation { get; set; }

        /// <summary>
        /// Gets or Sets ProjectSummary
        /// </summary>
        [DataMember(Name = "project_summary", EmitDefaultValue = true)]
        public Dictionary<string, string> ProjectSummary { get; set; }

        /// <summary>
        /// Gets or Sets MediationSystemPrompt
        /// </summary>
        [DataMember(Name = "mediation_system_prompt", EmitDefaultValue = true)]
        public string MediationSystemPrompt { get; set; }

        /// <summary>
        /// Whether to skip planning system or not.
        /// </summary>
        /// <value>Whether to skip planning system or not.</value>
        [DataMember(Name = "skip_planning", EmitDefaultValue = true)]
        public bool SkipPlanning { get; set; }

        /// <summary>
        /// List of tags associated with chat request
        /// </summary>
        /// <value>List of tags associated with chat request</value>
        [DataMember(Name = "tags", EmitDefaultValue = false)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Gets or Sets PlanningParams
        /// </summary>
        [DataMember(Name = "planning_params", EmitDefaultValue = true)]
        public ModelParameters PlanningParams { get; set; }

        /// <summary>
        /// Gets or Sets MediationParams
        /// </summary>
        [DataMember(Name = "mediation_params", EmitDefaultValue = true)]
        public ModelParameters MediationParams { get; set; }

        /// <summary>
        /// Gets or Sets Seed
        /// </summary>
        [DataMember(Name = "seed", EmitDefaultValue = true)]
        public int? Seed { get; set; }

        /// <summary>
        /// Gets or Sets Context
        /// </summary>
        [DataMember(Name = "context", EmitDefaultValue = true)]
        public string Context { get; set; }

        /// <summary>
        /// Gets or Sets HideReferences
        /// </summary>
        [DataMember(Name = "hide_references", EmitDefaultValue = true)]
        public bool? HideReferences { get; set; }

        /// <summary>
        /// Whether to use Muse Guard for chat request. Default to False.
        /// </summary>
        /// <value>Whether to use Muse Guard for chat request. Default to False.</value>
        [DataMember(Name = "muse_guard", EmitDefaultValue = true)]
        public bool MuseGuard { get; set; }

        /// <summary>
        /// Whether the chat request is for evaluation. Default is false.
        /// </summary>
        /// <value>Whether the chat request is for evaluation. Default is false.</value>
        [DataMember(Name = "evaluation", EmitDefaultValue = true)]
        public bool Evaluation { get; set; }

        /// <summary>
        /// Whether to use structured generation for planning. Default is false.
        /// </summary>
        /// <value>Whether to use structured generation for planning. Default is false.</value>
        [DataMember(Name = "structured_planning", EmitDefaultValue = true)]
        public bool StructuredPlanning { get; set; }

        /// <summary>
        /// Maximum number of structured planning steps. Default to 5.
        /// </summary>
        /// <value>Maximum number of structured planning steps. Default to 5.</value>
        [DataMember(Name = "max_structured_planning_steps", EmitDefaultValue = false)]
        public int MaxStructuredPlanningSteps { get; set; }

        /// <summary>
        /// Gets or Sets StructuredMediationRegex
        /// </summary>
        [DataMember(Name = "structured_mediation_regex", EmitDefaultValue = true)]
        public string StructuredMediationRegex { get; set; }

        /// <summary>
        /// Gets or Sets PlanningEndpoint
        /// </summary>
        [DataMember(Name = "planning_endpoint", EmitDefaultValue = true)]
        public PlanningEndpoint PlanningEndpoint { get; set; }

        /// <summary>
        /// Gets or Sets FrontDeskEndpoint
        /// </summary>
        [DataMember(Name = "front_desk_endpoint", EmitDefaultValue = true)]
        public FrontDeskEndpoint FrontDeskEndpoint { get; set; }

        /// <summary>
        /// Gets or Sets MediationEndpoint
        /// </summary>
        [DataMember(Name = "mediation_endpoint", EmitDefaultValue = true)]
        public MediationEndpoint MediationEndpoint { get; set; }

        /// <summary>
        /// Gets or Sets EmbeddingEndpoint
        /// </summary>
        [DataMember(Name = "embedding_endpoint", EmitDefaultValue = true)]
        public EmbeddingEndpoint EmbeddingEndpoint { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChatRequest {\n");
            sb.Append("  Prompt: ").Append(Prompt).Append("\n");
            sb.Append("  ConversationId: ").Append(ConversationId).Append("\n");
            sb.Append("  StreamResponse: ").Append(StreamResponse).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  UnityVersions: ").Append(UnityVersions).Append("\n");
            sb.Append("  DependencyInformation: ").Append(DependencyInformation).Append("\n");
            sb.Append("  ProjectSummary: ").Append(ProjectSummary).Append("\n");
            sb.Append("  MediationSystemPrompt: ").Append(MediationSystemPrompt).Append("\n");
            sb.Append("  SkipPlanning: ").Append(SkipPlanning).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  PlanningParams: ").Append(PlanningParams).Append("\n");
            sb.Append("  MediationParams: ").Append(MediationParams).Append("\n");
            sb.Append("  Seed: ").Append(Seed).Append("\n");
            sb.Append("  Context: ").Append(Context).Append("\n");
            sb.Append("  HideReferences: ").Append(HideReferences).Append("\n");
            sb.Append("  MuseGuard: ").Append(MuseGuard).Append("\n");
            sb.Append("  Evaluation: ").Append(Evaluation).Append("\n");
            sb.Append("  StructuredPlanning: ").Append(StructuredPlanning).Append("\n");
            sb.Append("  MaxStructuredPlanningSteps: ").Append(MaxStructuredPlanningSteps).Append("\n");
            sb.Append("  StructuredMediationRegex: ").Append(StructuredMediationRegex).Append("\n");
            sb.Append("  PlanningEndpoint: ").Append(PlanningEndpoint).Append("\n");
            sb.Append("  FrontDeskEndpoint: ").Append(FrontDeskEndpoint).Append("\n");
            sb.Append("  MediationEndpoint: ").Append(MediationEndpoint).Append("\n");
            sb.Append("  EmbeddingEndpoint: ").Append(EmbeddingEndpoint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
