/*
 * Muse API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Unity.Muse.Chat.Client.OpenAPIDateConverter;

namespace Unity.Muse.Chat.Model
{
    /// <summary>
    /// PlanningEndpoint
    /// </summary>
    [DataContract(Name = "PlanningEndpoint")]
    internal partial class PlanningEndpoint
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlanningEndpoint" /> class.
        /// </summary>
        /// <param name="varSystem">Planning endpoint parameters.</param>
        /// <param name="varClient">Client name for the endpoint.</param>
        /// <param name="apiKey">apiKey</param>
        /// <param name="baseUrl">baseUrl</param>
        /// <param name="apiVersion">apiVersion</param>
        /// <param name="model">Model name for the endpoint.</param>
        /// <param name="hfModelId">hfModelId</param>
        /// <param name="clientHash">clientHash</param>
        public PlanningEndpoint(string varSystem = @"&quot;planning&quot;", string varClient = @"&quot;&quot;", string apiKey = default(string), string baseUrl = default(string), string apiVersion = default(string), string model = @"&quot;&quot;", string hfModelId = default(string), string clientHash = default(string))
        {
            // use default value if no "varSystem" provided
            this.System = varSystem ?? @"&quot;planning&quot;";
            // use default value if no "varClient" provided
            this.VarClient = varClient ?? @"&quot;&quot;";
            this.ApiKey = apiKey;
            this.BaseUrl = baseUrl;
            this.ApiVersion = apiVersion;
            // use default value if no "model" provided
            this.Model = model ?? @"&quot;&quot;";
            this.HfModelId = hfModelId;
            this.ClientHash = clientHash;
        }

        /// <summary>
        /// Planning endpoint parameters.
        /// </summary>
        /// <value>Planning endpoint parameters.</value>
        [DataMember(Name = "system", EmitDefaultValue = false)]
        public string System { get; set; }

        /// <summary>
        /// Client name for the endpoint.
        /// </summary>
        /// <value>Client name for the endpoint.</value>
        [DataMember(Name = "client", EmitDefaultValue = false)]
        public string VarClient { get; set; }

        /// <summary>
        /// Gets or Sets ApiKey
        /// </summary>
        [DataMember(Name = "api_key", EmitDefaultValue = true)]
        public string ApiKey { get; set; }

        /// <summary>
        /// Gets or Sets BaseUrl
        /// </summary>
        [DataMember(Name = "base_url", EmitDefaultValue = true)]
        public string BaseUrl { get; set; }

        /// <summary>
        /// Gets or Sets ApiVersion
        /// </summary>
        [DataMember(Name = "api_version", EmitDefaultValue = true)]
        public string ApiVersion { get; set; }

        /// <summary>
        /// Model name for the endpoint.
        /// </summary>
        /// <value>Model name for the endpoint.</value>
        [DataMember(Name = "model", EmitDefaultValue = false)]
        public string Model { get; set; }

        /// <summary>
        /// Gets or Sets HfModelId
        /// </summary>
        [DataMember(Name = "hf_model_id", EmitDefaultValue = true)]
        public string HfModelId { get; set; }

        /// <summary>
        /// Gets or Sets ClientHash
        /// </summary>
        [DataMember(Name = "client_hash", EmitDefaultValue = true)]
        public string ClientHash { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlanningEndpoint {\n");
            sb.Append("  System: ").Append(System).Append("\n");
            sb.Append("  VarClient: ").Append(VarClient).Append("\n");
            sb.Append("  ApiKey: ").Append(ApiKey).Append("\n");
            sb.Append("  BaseUrl: ").Append(BaseUrl).Append("\n");
            sb.Append("  ApiVersion: ").Append(ApiVersion).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  HfModelId: ").Append(HfModelId).Append("\n");
            sb.Append("  ClientHash: ").Append(ClientHash).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
